In [46]:
import os
import pandas as pd

In [47]:
# importing data
df = pd.read_excel('Resources/CO_House_prices.xlsx')
df.head()

,CountyName,1997,1997.1,1997.2,1997.3,1997.4,1997.5,1997.6,1997.7,1997.8,...,2016.2,2016.3,2016.4,2016.5,2016.6,2016.7,2016.8,2016.9,2016.10,2016.11
0,Denver County,137645.0,139004.0,140457.0,141496.0,142674.0,143911.0,145010.0,145936.0,146793.0,...,363663.0,365549.0,368018.0,371348.0,374286.0,377192.0,380111.0,383043.0,385889.0,388619.0
1,El Paso County,139699.0,140358.0,141062.0,141691.0,142171.0,142477.0,142854.0,143113.0,143509.0,...,234461.0,236917.0,238308.0,240031.0,241531.0,243302.0,244869.0,246273.0,247775.0,249624.0
2,Arapahoe County,130120.0,130543.0,131002.0,131724.0,132453.0,133070.0,133495.0,133998.0,134750.0,...,278440.0,281270.0,284134.0,286542.0,289012.0,291454.0,293123.0,295157.0,297471.0,300119.0
3,Larimer County,161433.0,161747.0,162018.0,162237.0,162340.0,162536.0,162901.0,163436.0,163978.0,...,342499.0,345621.0,347420.0,350062.0,352542.0,356192.0,359330.0,361972.0,364883.0,367112.0
4,Pueblo County,87839.0,88350.0,88838.0,89398.0,89961.0,90483.0,90888.0,91280.0,91726.0,...,136237.0,137034.0,138265.0,139200.0,140275.0,141035.0,141913.0,142500.0,143091.0,143679.0

In [62]:
df.groupby(['CountyName']).mean()

,1997,1997.1,1997.2,1997.3,1997.4,1997.5,1997.6,1997.7,1997.8,1997.9,...,2016.2,2016.3,2016.4,2016.5,2016.6,2016.7,2016.8,2016.9,2016.10,2016.11
CountyName,,,,,,,,,,,,,,,,,,,,,
Adams County,124128.133333,124716.466667,125288.666667,125876.133333,126803.800000,127611.733333,128500.666667,129393.733333,130237.933333,131091.533333,...,286045.400000,289171.866667,292523.400000,295538.733333,298530.933333,300652.466667,302957.533333,305458.200000,308850.333333,312282.466667
Alamosa County,67003.500000,67262.000000,67488.000000,67377.500000,67439.000000,67504.000000,67612.500000,67719.000000,67809.000000,67988.000000,...,134127.666667,135068.000000,136179.333333,137463.666667,138299.333333,139619.666667,140757.000000,142377.666667,143495.333333,144725.333333
Arapahoe County,265646.357143,266803.428571,267554.571429,268416.928571,269303.714286,270251.785714,270482.571429,271196.000000,271526.571429,271943.571429,...,593179.214286,597711.928571,601564.571429,603935.357143,606780.642857,609992.785714,611803.214286,614521.785714,617557.142857,622414.785714
Archuleta County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,352586.500000,351552.000000,353619.500000,355649.000000,355632.000000,355798.500000,356710.000000,358934.500000,361235.500000,362498.000000
Baca County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61258.500000,61621.000000,61994.000000,62427.000000,62918.000000,63248.500000,63558.000000,63923.000000,64133.000000,64291.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Summit County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,432689.500000,438235.833333,443210.666667,446141.833333,449550.833333,452322.666667,456134.333333,461214.000000,468300.500000,474680.666667
Teller County,100278.800000,100695.400000,101434.200000,102118.400000,102824.600000,103295.400000,103925.800000,104385.600000,105063.200000,105720.000000,...,207903.800000,209255.000000,210499.200000,211526.200000,212750.600000,214064.200000,214784.200000,215403.000000,215956.000000,217254.200000
Washington County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91773.833333,93058.000000,94764.000000,96877.166667,98859.833333,101044.166667,102956.666667,104141.000000,104250.333333,104163.000000
Weld County,162607.777778,162711.333333,163195.888889,163515.481481,163955.259259,164042.148148,164208.851852,164575.481481,165380.814815,166400.851852,...,299542.034483,301108.172414,303129.724138,304745.655172,306929.448276,309177.103448,312790.689655,315950.206897,319626.724138,322056.517241
Yuma County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,143099.142857,144754.571429,146254.571429,148151.571429,149257.000000,150369.571429,151347.857143,152567.571429,153942.000000,154778.000000

In [60]:
county_list = df.CountyName.unique()
county_list

array(['Denver County', 'El Paso County', 'Arapahoe County',
       'Larimer County', 'Pueblo County', 'Jefferson County',
       'Adams County', 'Boulder County', 'Mesa County', 'Douglas County',
       'Weld County', 'Broomfield County', 'La Plata County',
       'Montrose County', 'Fremont County', 'Routt County',
       'Logan County', 'Morgan County', 'Montezuma County',
       'Alamosa County', 'Garfield County', 'Delta County',
       'Teller County', 'Moffat County', 'Elbert County', 'Eagle County',
       'Archuleta County', 'Summit County', 'Pitkin County',
       'Otero County', 'Gunnison County', 'Chaffee County',
       'Prowers County', 'Lake County', 'Park County',
       'Rio Grande County', 'Grand County', 'Kit Carson County',
       'Bent County', 'Clear Creek County', 'Yuma County',
       'Huerfano County', 'Rio Blanco County', 'Custer County',
       'Las Animas County', 'Phillips County', 'Ouray County',
       'Washington County', 'Costilla County', 'Saguache County',
       'Conejos County', 'Crowley County', 'Lincoln County',
       'Gilpin County', 'Baca County', 'San Miguel County',
       'Jackson County', 'Sedgwick County', 'Dolores County',
       'Kiowa County', 'Mineral County', 'Cheyenne County',
       'Hinsdale County', 'San Juan County'], dtype=object)

In [53]:
El_Paso_df[1997]

1      139699.0
27     114305.0
29     124579.0
34     238017.0
41     163244.0
52          NaN
81     144184.0
102         NaN
111    160237.0
117    212178.0
120         NaN
124     96762.0
194         NaN
200         NaN
219    150168.0
274     75436.0
290    118242.0
Name: 1997, dtype: float64