In [71]:
import os
import pandas as pd

In [72]:
# importing data
df = pd.read_excel('Resources/clean_House_prices.xlsx')
df.head()

,CountyName,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,Unnamed: 21
0,Denver County,144211.083333,157625.333333,175471.916667,202976.333333,232443.583333,246901.750000,249635.461538,254793.583333,261636.583333,...,249410.250000,241534.166667,243144.250000,233124.583333,241457.166667,267805.500000,295126.833333,334190.833333,373186.750000,NaN
1,El Paso County,142508.916667,147672.916667,155935.500000,163330.083333,177515.833333,186842.166667,192284.461538,198514.916667,209108.916667,...,214485.750000,206343.750000,207171.083333,197473.583333,198870.416667,208929.250000,214747.833333,224646.083333,240536.916667,NaN
2,Arapahoe County,133396.916667,143271.666667,158078.333333,180677.916667,206261.916667,215658.250000,218679.153846,220339.000000,223238.833333,...,194889.333333,183635.833333,183925.750000,171908.000000,177425.166667,201211.166667,220006.833333,253399.916667,287217.833333,NaN
3,Larimer County,163194.666667,168924.833333,181416.916667,196578.083333,218750.500000,233787.166667,239067.615385,245698.583333,249610.000000,...,245324.916667,242070.083333,243568.000000,240793.750000,247426.083333,263487.916667,283510.583333,315375.750000,351928.500000,NaN
4,Pueblo County,90495.750000,95448.666667,102374.000000,108664.583333,111731.000000,114387.333333,118079.000000,123091.500000,127394.583333,...,129389.916667,125860.500000,124227.750000,119524.250000,117125.416667,119618.500000,122145.916667,128119.083333,139482.166667,NaN

In [74]:
clean_df = df.groupby(['CountyName']).mean()
clean_df

,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,Unnamed: 21
CountyName,,,,,,,,,,,,,,,,,,,,,
Adams County,128133.405556,138042.472222,153253.533333,175973.177778,201303.355556,213591.866667,218562.133333,219396.283333,223075.427778,223455.261111,...,193579.572222,183917.588889,186966.950000,176663.405556,181639.650000,204357.177778,228642.094444,263220.038889,296396.388889,NaN
Alamosa County,67630.875000,66069.177778,69118.444444,73833.472222,77740.000000,82612.388889,85057.948718,88569.777778,91630.000000,93505.583333,...,96776.722222,97040.500000,95653.250000,93893.277778,98326.166667,106295.555556,113325.083333,126939.166667,138148.777778,NaN
Arapahoe County,269897.303571,281234.130952,314151.220238,360547.946429,409783.434524,428854.696429,434402.703297,440531.523810,458011.511905,469848.565476,...,449412.005952,441102.898810,440048.773810,420175.976190,430249.125000,469030.797619,496182.767857,553127.559524,604530.178571,NaN
Archuleta County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196484.400000,219535.166667,...,281004.666667,279217.791667,269932.500000,265868.625000,267919.458333,281679.166667,303034.041667,334200.625000,355895.333333,NaN
Baca County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58948.000000,...,43461.708333,43952.416667,41644.333333,40941.125000,42373.250000,44096.541667,49411.416667,56423.416667,62451.166667,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Summit County,NaN,NaN,223403.226852,250463.111111,263095.222222,273138.888889,281645.820513,294136.138889,304849.650000,328434.750000,...,380908.902778,381781.736111,368254.861111,355545.083333,358523.027778,369329.666667,389929.847222,406747.277778,447647.152778,NaN
Teller County,103601.833333,109636.100000,117109.483333,127863.416667,135530.633333,140564.316667,143391.707692,148258.133333,153925.366667,160435.816667,...,168542.616667,164747.633333,160741.550000,156623.966667,158510.216667,168053.266667,180082.533333,194769.433333,211584.016667,NaN
Washington County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,58917.000000,58473.166667,56912.083333,54184.333333,58249.000000,64038.916667,64225.083333,86096.755051,97781.527778,NaN
Weld County,164598.623457,173410.191358,190099.425926,205095.793210,225987.324074,242347.725862,249662.185676,255429.640805,259773.364943,258286.382184,...,228727.416667,218623.833333,212775.847701,206673.327586,213706.408046,229602.830460,254511.488506,284179.589080,307618.537356,NaN
Yuma County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97012.419444,97817.895833,...,99353.500000,97725.479167,98335.569444,99034.976190,102651.142857,110623.476190,120436.297619,131109.809524,147907.702381,NaN

In [75]:
county_list = df.CountyName.unique()
county_list

array(['Denver County', 'El Paso County', 'Arapahoe County',
       'Larimer County', 'Pueblo County', 'Jefferson County',
       'Adams County', 'Boulder County', 'Mesa County', 'Douglas County',
       'Weld County', 'Broomfield County', 'La Plata County',
       'Montrose County', 'Fremont County', 'Routt County',
       'Logan County', 'Morgan County', 'Montezuma County',
       'Alamosa County', 'Garfield County', 'Delta County',
       'Teller County', 'Moffat County', 'Elbert County', 'Eagle County',
       'Archuleta County', 'Summit County', 'Pitkin County',
       'Otero County', 'Gunnison County', 'Chaffee County',
       'Prowers County', 'Lake County', 'Park County',
       'Rio Grande County', 'Grand County', 'Kit Carson County',
       'Bent County', 'Clear Creek County', 'Yuma County',
       'Huerfano County', 'Rio Blanco County', 'Custer County',
       'Las Animas County', 'Phillips County', 'Ouray County',
       'Washington County', 'Costilla County', 'Saguache County',
       'Conejos County', 'Crowley County', 'Lincoln County',
       'Gilpin County', 'Baca County', 'San Miguel County',
       'Jackson County', 'Sedgwick County', 'Dolores County',
       'Kiowa County', 'Mineral County', 'Cheyenne County',
       'Hinsdale County', 'San Juan County'], dtype=object)

In [77]:
clean_df.to_csv('Resources/data_visualize.csv', index=False)